from typing import Final


TEXTS_ES: Final[dict[str, str]] = {
    "app_title": "DataSet Gen App",
    "app_subtitle": "Generación de datasets con modelos de IA",

    "header_model": "Modelo",
    "header_export": "Exportación",
    "not_selected": "No seleccionado",

    "step_1": "Subir video",
    "step_2": "Seleccionar modelo",
    "step_3": "Ruta de exportación",
    "step_4": "Ejecutar análisis",
    "step_5": "Revisar generados",
    "step_6": "Terminar",

    "upload_title": "Subir video",
    "upload_description": "Selecciona el video que será analizado para generar el dataset.",
    "select_video": "Seleccionar video",
    "change_video": "Cambiar video",
    "video_dialog_title": "Seleccionar video para analizar",
    "video_filter": "Videos (*.mp4 *.avi *.mov *.mkv *.m4v);;Todos los archivos (*)",

    "preview_empty": "Selecciona un video para mostrar la vista previa",
    "play": "Reproducir",
    "pause": "Pausar",
    "stop": "Detener",

    "preview_title": "Vista previa del video",
    "video_information": "Información del video",
    "video_name": "Archivo",
    "video_resolution": "Resolución",
    "video_fps": "FPS",
    "video_duration": "Duración",
    "video_size": "Tamaño",
    "video_path": "Ruta",

    "progress_title": "Progreso del análisis",
    "progress_waiting": "Esperando configuración",
    "cancel": "Cancelar",
    "previous": "Regresar",
    "continue": "Continuar",

    "placeholder_title": "Siguiente paso",
    "placeholder_model_message": "Aquí configuraremos el modelo de IA que se utilizará para analizar el video.",

    "video_error_title": "No se pudo abrir el video",
    "video_error_message": "El archivo seleccionado no pudo ser leído correctamente.",

    "time_empty": "00:00 / 00:00",

    "model_title": "Seleccionar modelo",
    "model_description": "Selecciona y valida el modelo de IA que se utilizará para analizar el video.",
    "select_model": "Seleccionar modelo",
    "change_model": "Cambiar modelo",
    "model_information": "Información del modelo",
    "model_file": "Archivo",
    "model_format": "Formato",
    "model_size": "Tamaño",
    "model_device": "Dispositivo validado",
    "model_path": "Ruta",
    "model_status": "Estado",
    "model_empty": "Selecciona un modelo .pt, .onnx o .engine",
    "model_note_title": "Compatibilidad del equipo",
    "model_note": "La aplicación comprobará que el modelo pueda ejecutarse en este dispositivo antes de permitir continuar.",
    "model_dialog_title": "Seleccionar modelo de IA",
    "model_filter": "Modelos compatibles (*.pt *.onnx *.engine);;Todos los archivos (*)",
    "model_error_title": "Modelo no compatible",
    "model_error_message": "El modelo seleccionado no pudo validarse en este dispositivo.",
    "model_validating": "Validando modelo...",
    "model_valid": "Modelo compatible",
    "format_pytorch": "PyTorch (.pt)",
    "format_onnx": "ONNX (.onnx)",
    "format_tensorrt": "TensorRT (.engine)",
    "backend_cpu": "CPU",
    "backend_mps": "Apple Metal (MPS)",
    "backend_cuda": "CUDA",
    "backend_tensorrt": "TensorRT",
    "placeholder_export_message": "Aquí seleccionaremos la carpeta donde se guardará el dataset generado.",

    "validation_dialog_title": "Validación del modelo",
    "model_validating": "Validando modelo...",
    "model_validating_description": "La aplicación está cargando el modelo y comprobando que pueda ejecutarse en este dispositivo.",

    "export_title": "Ruta de exportación",
    "export_description": "Selecciona la carpeta donde se generará la estructura del dataset.",
    "select_export_path": "Seleccionar carpeta",
    "change_export_path": "Cambiar carpeta",
    "export_information": "Destino seleccionado",
    "export_base_directory": "Carpeta base",
    "export_workspace": "Carpeta de generación",
    "export_status": "Estado",
    "export_empty": "Aún no se ha seleccionado una carpeta de exportación.",
    "export_ready": "Ruta seleccionada. La estructura se creará al continuar.",
    "export_structure_title": "Estructura que se generará",
    "export_structure_preview": "GeneratedDataSet_fecha_hora/\n├── images/\n├── labels/\n├── previews/\n└── Info.txt",
    "export_dialog_title": "Seleccionar carpeta de exportación",
    "export_error_title": "No se pudo preparar la exportación",
    "export_error_message": "No fue posible crear la estructura del dataset en la carpeta seleccionada.",
    "placeholder_analysis_message": "Aquí ejecutaremos el análisis del video utilizando el modelo seleccionado.",

    "analysis_warning_text_short": "Adevertencia, el proceso puede tardar y usar CPU/GPU, memoria y almacenamiento en gran medida, se recomienda cerrar otras aplicacioens",
    "analysis_title": "Ejecutar análisis",
    "analysis_description": "El video será procesado con el modelo seleccionado para generar imágenes, etiquetas y vistas previas del dataset.",
    "analysis_warning_title": "Antes de iniciar",
    "analysis_warning_text": "Este proceso puede tardar varios minutos y utilizar una cantidad considerable de CPU, GPU, memoria y almacenamiento. Evita cerrar la aplicación mientras se ejecuta el análisis.",
    "analysis_video_fps": "FPS del video",
    "analysis_target_fps": "FPS de extracción",
    "analysis_total_frames": "Frames totales",
    "analysis_analyzed_frames": "Frames analizados",
    "analysis_remaining_frames": "Frames restantes",
    "analysis_processed_video_time": "Tiempo de video abarcado",
    "analysis_elapsed_time": "Tiempo transcurrido",
    "analysis_estimated_time": "Tiempo estimado restante",
    "analysis_processing_rate": "Velocidad",
    "analysis_processed_video_time": "Video abarcado",
    "analysis_estimated_time": "Restante estimado",
    "analysis_elapsed_time": "Transcurrido",
    "analysis_saved_images": "Imágenes",
    "analysis_saved_labels": "Etiquetas",
    "analysis_detections": "Detecciones",
    "analysis_status": "Estado",
    "analysis_status_ready": "Listo para iniciar",
    "analysis_status_running": "Analizando video",
    "analysis_status_paused": "Análisis pausado",
    "analysis_status_cancelled": "Análisis cancelado",
    "analysis_status_finished": "Análisis finalizado",
    "start_analysis": "Iniciar proceso",
    "pause_analysis": "Pausar",
    "resume_analysis": "Reanudar",
    "cancel_analysis": "Cancelar análisis",
    "cancel_analysis_title": "Cancelar análisis",
    "cancel_analysis_message": "¿Seguro que deseas cancelar el análisis? Se eliminarán los archivos generados durante este proceso.",


    "analysis_finished_title": "Proceso terminado",
    "analysis_finished_message": "El análisis finalizó correctamente. Puedes continuar a la siguiente ventana.",
    "progress_title": "Progreso del análisis",
    "progress_waiting": "Esperando configuración",
    "placeholder_analysis_message": "Aquí se mostrarán los resultados generados.",

    
}


def text(key: str) -> str:
    return TEXTS_ES[key]